name: 'Container Action Template (PowerShell edition)'
description: 'Get started with Container actions using PowerShell'
author: 'TylerLeonhardt'
inputs: 
  subscriptionName:
    description: 'Subscription to use'
    required: true
  planName:
    description: 'plan to use'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - -SubscriptionName
    - ${{ inputs.subscriptionName }}
    - -PlanName
    - ${{ inputs.planName }}
